// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Collector_CheckAddresses_FullMethodName = "/telemetry.Collector/CheckAddresses"
	Collector_CheckPacket_FullMethodName    = "/telemetry.Collector/CheckPacket"
)

// CollectorClient is the client API for Collector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorClient interface {
	CheckAddresses(ctx context.Context, in *Addresses, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CheckPacket(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RawPacket, Alert], error)
}

type collectorClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorClient(cc grpc.ClientConnInterface) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) CheckAddresses(ctx context.Context, in *Addresses, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Collector_CheckAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) CheckPacket(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RawPacket, Alert], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Collector_ServiceDesc.Streams[0], Collector_CheckPacket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RawPacket, Alert]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Collector_CheckPacketClient = grpc.ClientStreamingClient[RawPacket, Alert]

// CollectorServer is the server API for Collector service.
// All implementations must embed UnimplementedCollectorServer
// for forward compatibility.
type CollectorServer interface {
	CheckAddresses(context.Context, *Addresses) (*emptypb.Empty, error)
	CheckPacket(grpc.ClientStreamingServer[RawPacket, Alert]) error
	mustEmbedUnimplementedCollectorServer()
}

// UnimplementedCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServer struct{}

func (UnimplementedCollectorServer) CheckAddresses(context.Context, *Addresses) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAddresses not implemented")
}
func (UnimplementedCollectorServer) CheckPacket(grpc.ClientStreamingServer[RawPacket, Alert]) error {
	return status.Error(codes.Unimplemented, "method CheckPacket not implemented")
}
func (UnimplementedCollectorServer) mustEmbedUnimplementedCollectorServer() {}
func (UnimplementedCollectorServer) testEmbeddedByValue()                   {}

// UnsafeCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServer will
// result in compilation errors.
type UnsafeCollectorServer interface {
	mustEmbedUnimplementedCollectorServer()
}

func RegisterCollectorServer(s grpc.ServiceRegistrar, srv CollectorServer) {
	// If the following call panics, it indicates UnimplementedCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Collector_ServiceDesc, srv)
}

func _Collector_CheckAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Addresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).CheckAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Collector_CheckAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).CheckAddresses(ctx, req.(*Addresses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_CheckPacket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServer).CheckPacket(&grpc.GenericServerStream[RawPacket, Alert]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Collector_CheckPacketServer = grpc.ClientStreamingServer[RawPacket, Alert]

// Collector_ServiceDesc is the grpc.ServiceDesc for Collector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Collector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAddresses",
			Handler:    _Collector_CheckAddresses_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CheckPacket",
			Handler:       _Collector_CheckPacket_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}
