// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Addresses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ipaddrv4      []byte                 `protobuf:"bytes,2,opt,name=ipaddrv4,proto3" json:"ipaddrv4,omitempty"`
	Ipaddrv6      []byte                 `protobuf:"bytes,3,opt,name=ipaddrv6,proto3" json:"ipaddrv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Addresses) Reset() {
	*x = Addresses{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Addresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addresses) ProtoMessage() {}

func (x *Addresses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addresses.ProtoReflect.Descriptor instead.
func (*Addresses) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Addresses) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Addresses) GetIpaddrv4() []byte {
	if x != nil {
		return x.Ipaddrv4
	}
	return nil
}

func (x *Addresses) GetIpaddrv6() []byte {
	if x != nil {
		return x.Ipaddrv6
	}
	return nil
}

type RawPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packet        []byte                 `protobuf:"bytes,1,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPacket) Reset() {
	*x = RawPacket{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacket) ProtoMessage() {}

func (x *RawPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacket.ProtoReflect.Descriptor instead.
func (*RawPacket) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *RawPacket) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

type Alert struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AttackDetected bool                   `protobuf:"varint,1,opt,name=attack_detected,json=attackDetected,proto3" json:"attack_detected,omitempty"`
	CntSynPkg      uint64                 `protobuf:"varint,2,opt,name=cnt_syn_pkg,json=cntSynPkg,proto3" json:"cnt_syn_pkg,omitempty"`
	Target         string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetAttackDetected() bool {
	if x != nil {
		return x.AttackDetected
	}
	return false
}

func (x *Alert) GetCntSynPkg() uint64 {
	if x != nil {
		return x.CntSynPkg
	}
	return 0
}

func (x *Alert) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\ttelemetry\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"}\n" +
	"\tAddresses\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bipaddrv4\x18\x02 \x01(\fR\bipaddrv4\x12\x1a\n" +
	"\bipaddrv6\x18\x03 \x01(\fR\bipaddrv6\"#\n" +
	"\tRawPacket\x12\x16\n" +
	"\x06packet\x18\x01 \x01(\fR\x06packet\"h\n" +
	"\x05Alert\x12'\n" +
	"\x0fattack_detected\x18\x01 \x01(\bR\x0eattackDetected\x12\x1e\n" +
	"\vcnt_syn_pkg\x18\x02 \x01(\x04R\tcntSynPkg\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target2\x84\x01\n" +
	"\tCollector\x12>\n" +
	"\x0eCheckAddresses\x12\x14.telemetry.Addresses\x1a\x16.google.protobuf.Empty\x127\n" +
	"\vCheckPacket\x12\x14.telemetry.RawPacket\x1a\x10.telemetry.Alert(\x01B\x11Z\x0fproto/telemetryb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_telemetry_proto_goTypes = []any{
	(*Addresses)(nil),             // 0: telemetry.Addresses
	(*RawPacket)(nil),             // 1: telemetry.RawPacket
	(*Alert)(nil),                 // 2: telemetry.Alert
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_proto_telemetry_proto_depIdxs = []int32{
	3, // 0: telemetry.Addresses.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: telemetry.Collector.CheckAddresses:input_type -> telemetry.Addresses
	1, // 2: telemetry.Collector.CheckPacket:input_type -> telemetry.RawPacket
	4, // 3: telemetry.Collector.CheckAddresses:output_type -> google.protobuf.Empty
	2, // 4: telemetry.Collector.CheckPacket:output_type -> telemetry.Alert
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
