syntax = "proto3";

package telemetry;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

option go_package = "proto/telemetry";

message Addresses {
    google.protobuf.Timestamp timestamp = 1;
    bytes ipaddrv4 = 2;
    bytes ipaddrv6 = 3;
}

message RawPacket {
    bytes packet = 1;
}

message Alert {
    bool attack_detected = 1;
    uint64 cnt_syn_pkg = 2;
    string target = 3;
}

service Collector {
    rpc CheckAddresses(Addresses) returns (google.protobuf.Empty);
    rpc CheckPacket(stream RawPacket) returns (Alert);
}